/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '//': RouteRecordInfo<
      '//',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/favorites/': RouteRecordInfo<
      '/favorites/',
      '/favorites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photo/[id]': RouteRecordInfo<
      '/photo/[id]',
      '/photo/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index/index.vue': {
      routes:
        | '//'
      views:
        | never
    }
    'src/pages/index/index@header.vue': {
      routes:
        | '//'
      views:
        | never
    }
    'src/pages/favorites/index.vue': {
      routes:
        | '/favorites/'
      views:
        | never
    }
    'src/pages/favorites/index@header.vue': {
      routes:
        | '/favorites/'
      views:
        | never
    }
    'src/pages/photo/[id].vue': {
      routes:
        | '/photo/[id]'
      views:
        | never
    }
    'src/pages/photo/[id]@header.vue': {
      routes:
        | '/photo/[id]'
      views:
        | never
    }
    'src/pages/search/index.vue': {
      routes:
        | '/search/'
      views:
        | never
    }
    'src/pages/search/index@header.vue': {
      routes:
        | '/search/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
